global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['172.31.31.102:9090']  # Replace with your Prometheus server address
    ec2_sd_configs:
      - region: us-east-1
# scrape_configs:
#   - job_name: 'prometheus'
#     static_configs:
#       - targets: ['localhost:9090']
